# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`


In [2]:
# 1. Import the numpy package under the name np (★☆☆)
# hint: import … as
    
import numpy
import numpy as np     

In [16]:
# 2. Create a null vector of size 10 (★☆☆)
hint: np.zeros

x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
# 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
#hint: array[4]

x[4]=1
print(x)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [19]:
# 4. Create a vector with values ranging from 10 to 49 (★☆☆)
# hint: arange
y = np.arange(10,49)
print(y)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [26]:
#5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
#hint: reshape

z = np.arange(0, 9).reshape((3, 3))
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [39]:
# 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
#hint: np.nonzero

#incorrect!
w = [1,2,0,0,4,0]
numpy.nonzero(w)
print(w) #incorrect

i = numpy.nonzero([1,2,0,0,4,0])
print(i)

[1, 2, 0, 0, 4, 0]
(array([0, 1, 4]),)


In [31]:
#7. Create a 3x3 identity matrix (★☆☆)
#hint: np.eye

b = np.eye(3,3)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
#8. Create a 3x3x3 array with random values (★☆☆)
#hint: np.random.random

c = np.random.random((3,3,3))
print(c)

[[[0.29204656 0.74163671 0.91779939]
  [0.38937018 0.37590851 0.59684802]
  [0.78475326 0.40681711 0.76672172]]

 [[0.16090509 0.60291174 0.26328611]
  [0.9962035  0.63456835 0.95945712]
  [0.89321092 0.63230562 0.46765689]]

 [[0.67522644 0.44805292 0.50928235]
  [0.68656752 0.57051388 0.60071904]
  [0.47519408 0.98647049 0.89826033]]]


In [42]:
# 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
# hint: min, max

d = np.random.random((10,10))
print(d)

[[0.54021901 0.70478881 0.05117607 0.5723591  0.7585809  0.99350801
  0.36263066 0.77520298 0.52739986 0.43855854]
 [0.45813176 0.53869856 0.88101958 0.02946151 0.27301679 0.91343188
  0.36782002 0.60416677 0.63936733 0.22857011]
 [0.67574138 0.26582265 0.93494622 0.92987949 0.5372603  0.89555772
  0.07434848 0.85048059 0.55688996 0.09533268]
 [0.8649337  0.29443184 0.92421022 0.52475628 0.13412432 0.86443706
  0.90011989 0.42165712 0.60521849 0.37751377]
 [0.99430958 0.11268379 0.81346787 0.80480265 0.46351637 0.82144021
  0.62593531 0.08754857 0.80807318 0.61515843]
 [0.34860922 0.59733289 0.277341   0.95481544 0.35591319 0.18199382
  0.90320097 0.24689213 0.39940891 0.27360427]
 [0.66744535 0.02352427 0.34809317 0.94872216 0.44668084 0.04740719
  0.47717376 0.0317521  0.79976699 0.73450508]
 [0.93507223 0.53243348 0.8455415  0.94869091 0.6936899  0.90550212
  0.41338133 0.72255857 0.30624546 0.7916375 ]
 [0.24930829 0.80885803 0.38280797 0.77058051 0.28403709 0.90355165
  0.21669081

In [45]:
e=np.min(d)
print(e)
f=np.max(d)
print(f)

0.01138095501887082
0.994309581268533


In [46]:
# 10. Create a random vector of size 30 and find the mean value (★☆☆)
# hint: mean

g = np.random.random((30))
print(g)
    

[0.05765532 0.8701584  0.77370527 0.5312227  0.30821458 0.97585042
 0.53481054 0.50569481 0.04111803 0.47785838 0.97869234 0.84242155
 0.94199865 0.30901636 0.65748962 0.22847114 0.91449913 0.34508335
 0.45435022 0.79584387 0.94277951 0.98816083 0.72335306 0.9712869
 0.71551878 0.32739012 0.22351356 0.59324191 0.19099524 0.22401833]


In [48]:
h = np.mean(g)
print(h)

0.5814804303209176


In [95]:
# 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
# hint: np.diag

j = np.diag(1+np.arange(4),k=-1)
print(j)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [77]:
#12. Normalize a 5x5 random matrix (★☆☆)
#hint: (x -mean)/std

k = np.random.random((5,5))
print(k)



[[0.39839583 0.09058002 0.02258364 0.63316373 0.38650102]
 [0.23248431 0.97617563 0.04600141 0.47968266 0.49979056]
 [0.81960822 0.89823227 0.69357667 0.07901349 0.57127179]
 [0.16504986 0.57476835 0.43007951 0.26592377 0.35484736]
 [0.05557776 0.28085932 0.93527833 0.82303875 0.10453827]]


In [87]:
kmax, kmin = k.max(), k.min()
k = (k - kmin) / (kmax - kmin)
print(f"After normalization: {x})")

After normalization: [[0.44334121 0.15452661 0.19898455 0.50822836 0.87473883]
 [0.70618918 0.22465967 0.96933221 0.7035091  0.02383191]
 [0.80201503 0.         0.80658827 1.         0.28433636]
 [0.48749017 0.3106105  0.11012955 0.61323943 0.88342252]
 [0.12011739 0.24559918 0.232863   0.96443756 0.90755028]])


In [102]:
# 13. How to find common values between two arrays? (★☆☆)
#hint: np.intersect1d

o = np.random.randint(50, size=((3,3)))
print(o)

[[15  5  5]
 [16 41  7]
 [39 36 15]]


In [103]:
p = np.random.randint(50, size=((3,3)))
print(p)

[[34 12 14]
 [ 9 11 27]
 [44 15 43]]


In [107]:
r=np.intersect1d(o,p)
print(r)

[15]


In [111]:
#14. Create a random vector of size 10 and sort it (★★☆)
#hint: sort

q = np.random.random(10)
print(q)

[0.19187756 0.80387903 0.89887353 0.75215302 0.36777103 0.12654328
 0.93839067 0.94669853 0.26960007 0.8746249 ]


In [114]:
r = np.sort(q)
print(r)

[0.12654328 0.19187756 0.26960007 0.36777103 0.75215302 0.80387903
 0.8746249  0.89887353 0.93839067 0.94669853]


In [137]:
#15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
#hint: argmax

s = np.random.random(10)
print(s)

mx_s = max(s)
print(mx_s)

s[s.argmax()]=0
print(s)

[0.40710715 0.94124052 0.04506532 0.79911039 0.08683531 0.91212571
 0.76336747 0.37022262 0.67859364 0.61000522]
0.9412405200807977
[0.40710715 0.         0.04506532 0.79911039 0.08683531 0.91212571
 0.76336747 0.37022262 0.67859364 0.61000522]


In [138]:
#16. Subtract the mean of each row of a matrix (★★☆)
#hint: mean(axis=,keepdims=)

a = np.random.rand(3, 4)
print(a)

b = a - a.mean(axis=1, keepdims=True)
print(b)

[[0.2119385  0.20258151 0.53624602 0.95756544]
 [0.1729811  0.74870222 0.82299805 0.0738217 ]
 [0.70159957 0.9974701  0.97216405 0.55655576]]
[[-0.26514437 -0.27450135  0.05916315  0.48048257]
 [-0.28164467  0.29407645  0.36837228 -0.38080407]
 [-0.1053478   0.19052273  0.16521668 -0.25039161]]


In [142]:
#17. How to get the n largest values of an array (★★★)
#Z = np.arange(10000)
#np.random.shuffle(Z)
#n = 5
#hint: np.argsort | np.argpartition

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(Z)

sorted_index_array = np.argsort(Z)
sorted_array = Z[sorted_index_array]
print("Sorted array:", sorted_array)
rslt = sorted_array[-n : ]
print("{} largest value:".format(n),rslt)



[6709 6120 7446 ... 6544 6693 1361]
Sorted array: [   0    1    2 ... 9997 9998 9999]
5 largest value: [9995 9996 9997 9998 9999]


In [156]:
#18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example: 6 --> 36)
#hint: np.where

x = np.random.random((5,3))
print(x)
x_new= np.where(x<= 4, x, x**2)
print(x_new)


[[0.18942102 0.87938319 0.24656053]
 [0.71900672 0.20885702 0.92363079]
 [0.75319787 0.35072687 0.13422972]
 [0.04649983 0.3036916  0.00520692]
 [0.95268189 0.51798254 0.12267088]]
[[0.18942102 0.87938319 0.24656053]
 [0.71900672 0.20885702 0.92363079]
 [0.75319787 0.35072687 0.13422972]
 [0.04649983 0.3036916  0.00520692]
 [0.95268189 0.51798254 0.12267088]]
